version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket <YOUR_S3_BUCKET_NAME> --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml
