AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Python Lambda Deployment

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Timeout: 10
      MemorySize: 128
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
